language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alimuratkuslu/kelimeoyunu-backend -f Dockerfile .
  - docker build -t alimuratkuslu/kelimeoyunu-frontend -f ./frontend/Dockerfile ./frontend

after_succes:
  - docker build -t alimuratkuslu/kelimeoyunu-backend -f Dockerfile .
  - docker build -t alimuratkuslu/kelimeoyunu-frontend -f ./frontend/Dockerfile ./frontend
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push alimuratkuslu/kelimeoyunu-backend
  - docker push alimuratkuslu/kelimeoyunu-frontend

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'test-multi-docker'
  env: 'Test-multi-docker-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-227384213485'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY