language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alimuratkuslu/kelimeoyunu-backend -f Dockerfile .
  - docker build -t alimuratkuslu/kelimeoyunu-frontend -f ./frontend/Dockerfile ./frontend

after_succes:
  - docker build -t alimuratkuslu/kelimeoyunu-backend -f Dockerfile .
  - docker build -t alimuratkuslu/kelimeoyunu-frontend -f ./frontend/Dockerfile ./frontend



