sudo: required
services:
  - docker

before_install:
  - docker build -t alimuratkuslu/kelimeoyunu-backend -f Dockerfile .
  - docker build -t alimuratkuslu/kelimeoyunu-frontend -f ./frontend/Dockerfile ./frontend

script: 
  - docker run -e CI=true alimuratkuslu/kelimeoyunu-frontend npm run test -- --coverage

after_succes:
  - docker build -t alimuratkuslu/kelimeoyunu-backend -f Dockerfile .
  - docker build -t alimuratkuslu/kelimeoyunu-frontend -f ./frontend/Dockerfile ./frontend



